<?php
return [
    0 => ['name' => 'Moras', 'rank' => 1],
    1 => ['name' => 'Plume de Stormterror', 'rank' => 5, 'obtention' => 12],
    2 => ['name' => 'Griffe de Stormterror', 'rank' => 5, 'obtention' => 12],
    3 => ['name' => 'Souffle de Stormterror', 'rank' => 5, 'obtention' => 12],
    4 => ['name' => 'Queue de Borée', 'rank' => 5, 'obtention' => 13],
    5 => ['name' => 'Vertèbre de Borée', 'rank' => 5, 'obtention' => 13],
    6 => ['name' => 'Esprit de Borée', 'rank' => 5, 'obtention' => 13],
    7 => ['name' => 'Corne de Monoceros', 'rank' => 5, 'obtention' => 14],
    8 => ['name' => 'Fragment du démon', 'rank' => 5, 'obtention' => 14],
    9 => ['name' => 'Ombre du guerrier', 'rank' => 5, 'obtention' => 14],
    10 => ['name' => 'Couronne du roi dragon', 'rank' => 5, 'obtention' => 15],
    11 => ['name' => 'Branche de jade cramoisi', 'rank' => 5, 'obtention' => 15],
    12 => ['name' => 'Ecaille dorée', 'rank' => 5, 'obtention' => 15],
    13 => ['name' => 'Moment de fusion', 'rank' => 5, 'obtention' => 16],
    14 => ['name' => 'Papillon infernal', 'rank' => 5, 'obtention' => 16],
    15 => ['name' => 'Coeur de cendre', 'rank' => 5, 'obtention' => 16],
    16 => ['name' => 'Graine d\'ouragan', 'rank' => 4],
    17 => ['name' => 'Prisme d\'éclair', 'rank' => 4],
    18 => ['name' => 'Pilier de basalte', 'rank' => 4],
    19 => ['name' => 'Duramen de glace', 'rank' => 4],
    20 => ['name' => 'Graine de feu', 'rank' => 4],
    21 => ['name' => 'Coeur d\'eau pure', 'rank' => 4],
    22 => ['name' => 'Jade juvénile', 'rank' => 4],
    23 => ['name' => 'Fleur cristalline', 'rank' => 4],
    24 => ['name' => 'Mécanisme oni', 'rank' => 4],
    25 => ['name' => 'Coeur perpétuel', 'rank' => 4],
    26 => ['name' => 'Perle brûlante', 'rank' => 4],
    27 => ['name' => 'Rosée du rejet', 'rank' => 4],
    28 => ['name' => 'Perles tempestives', 'rank' => 4],
    29 => ['name' => 'Régalia de faille', 'rank' => 4],
    30 => ['name' => 'Morceau de diamant scintillant', 'rank' => 4],
    31 => ['name' => 'Morceau d\'agate agnidus', 'rank' => 4],
    32 => ['name' => 'Morceau de lazurite varunada', 'rank' => 4],
    33 => ['name' => 'Morceau d\'améthyste vajrada', 'rank' => 5],
    34 => ['name' => 'Morceau de turquoise vayuda', 'rank' => 4],
    35 => ['name' => 'Morceau de jade shivada', 'rank' => 4],
    36 => ['name' => 'Morceau de topaze prithiva', 'rank' => 4],
    37 => ['name' => 'Fragment dispersé de Décabarian', 'rank' => 4],
    38 => ['name' => 'Croc fendu du Loup boréal', 'rank' => 4],
    39 => ['name' => 'Menottes du Chevalier du Croc de Lion', 'rank' => 4],
    40 => ['name' => 'Squelette sacré de Guyun', 'rank' => 4],
    41 => ['name' => 'Agent karstique', 'rank' => 4],
    42 => ['name' => 'Fragment d\'aérosidérite noire', 'rank' => 4],
    43 => ['name' => 'Branche marine de jade', 'rank' => 4],
    44 => ['name' => 'Affection de Narukami', 'rank' => 4],
    45 => ['name' => 'Masque du cornu', 'rank' => 4],
    46 => ['name' => 'Corne à cristal noir', 'rank' => 4],
    47 => ['name' => 'Pousse des lignes énergétiques', 'rank' => 4],
    48 => ['name' => 'Mèches d\'herbe brumeuse', 'rank' => 4],
    49 => ['name' => 'Grande dague de l\'Inspecteur', 'rank' => 4],
    50 => ['name' => 'Fragment d\'os fossilisé', 'rank' => 4],
    52 => ['name' => 'Noyau du chaos', 'rank' => 4],
    53 => ['name' => 'Oeil du chaos', 'rank' => 4],
    54 => ['name' => 'Prisme polarisant', 'rank' => 4],
    55 => ['name' => 'Serre dissimulée', 'rank' => 4],
    56 => ['name' => 'Philosophie de la Liberté', 'rank' => 4],
    57 => ['name' => 'Philosophie de la Résistance', 'rank' => 4],
    58 => ['name' => 'Philosophie de la Poésie', 'rank' => 4],
    59 => ['name' => 'Philosophie de la Prospérité', 'rank' => 4],
    60 => ['name' => 'Philosophie de la Diligence', 'rank' => 4],
    61 => ['name' => 'Philosophie de l\'Or', 'rank' => 4],
    62 => ['name' => 'Philosophie de l\'éphémère', 'rank' => 4],
    63 => ['name' => 'Philosophie de l\'élégance', 'rank' => 4],
    64 => ['name' => 'Philosophie de la lumière', 'rank' => 4],
    65 => ['name' => 'Fragment de diamant scintillant', 'rank' => 3],
    66 => ['name' => 'Fragment d\'agate agnidus', 'rank' => 3],
    67 => ['name' => 'Fragment de lazurite vanurada', 'rank' => 3],
    68 => ['name' => 'Fragment d\'améthyste vajrada', 'rank' => 3],
    69 => ['name' => 'Fragment de turquoise vayuda', 'rank' => 3],
    70 => ['name' => 'Fragment de jade shivada', 'rank' => 3],
    71 => ['name' => 'Fragment de topaze prithiva', 'rank' => 3],
    72 => ['name' => 'Mur abattu de Décabarian', 'rank' => 3],
    73 => ['name' => 'Croc brisé du Loup boréal', 'rank' => 3],
    74 => ['name' => 'Chaînes du Chevalier du Croc de Lion', 'rank' => 3],
    75 => ['name' => 'Roche lustrée de Guyun', 'rank' => 3],
    76 => ['name' => 'Mercure karstique', 'rank' => 3],
    77 => ['name' => '&Eacute;clat d\'aérosidérite noire', 'rank' => 3],
    78 => ['name' => 'Branche marine de gemme', 'rank' => 3],
    79 => ['name' => 'Joie de Narukami', 'rank' => 3],
    80 => ['name' => 'Masque de la morsure du tigre', 'rank' => 3],
    81 => ['name' => 'Masque sinistre', 'rank' => 3],
    82 => ['name' => 'Parchemin maudit', 'rank' => 3],
    83 => ['name' => 'Pointe de flèche usée', 'rank' => 3],
    85 => ['name' => 'Feuilles mortes des lignes énergétiques', 'rank' => 3],
    86 => ['name' => 'Herbe brumeuse', 'rank' => 3],
    87 => ['name' => 'Dague rituelle de l\'Usurier', 'rank' => 3],
    88 => ['name' => 'Insigne d\'officier', 'rank' => 3],
    89 => ['name' => 'Essence de Blob', 'rank' => 3],
    90 => ['name' => 'Nectar élémentaire', 'rank' => 3],
    91 => ['name' => 'Fragment d\'os solide', 'rank' => 3],
    92 => ['name' => 'Insigne de corbeau en or', 'rank' => 3],
    93 => ['name' => 'Circuit du chaos', 'rank' => 3],
    94 => ['name' => 'Garde-main célèbre', 'rank' => 3],
    95 => ['name' => 'Axe du chaos', 'rank' => 3],
    96 => ['name' => 'Prisme de cristal', 'rank' => 3],
    97 => ['name' => 'Noyau spectral', 'rank' => 3],
    98 => ['name' => 'Ongle dissimulé', 'rank' => 3],
    99 => ['name' => 'Guide de la Liberté', 'rank' => 3],
    100 => ['name' => 'Guide de la Résistance', 'rank' => 3],
    101 => ['name' => 'Guide de la Poésie', 'rank' => 3],
    102 => ['name' => 'Guide de la Prospérité', 'rank' => 3],
    103 => ['name' => 'Guide de la Diligence', 'rank' => 3],
    104 => ['name' => 'Guide de l\'Or', 'rank' => 3],
    105 => ['name' => 'Guide de l\'&Eacute;phémère', 'rank' => 3],
    106 => ['name' => 'Guide de l\'&Eacute;légance', 'rank' => 3],
    107 => ['name' => 'Guide de la Lumière', 'rank' => 3],
    108 => ['name' => '&Eacute;clat de diamant scintillant', 'rank' => 2],
    109 => ['name' => '&Eacute;clat d\'agate agnidus', 'rank' => 2],
    110 => ['name' => '&Eacute;clat de lazurite varunada', 'rank' => 2],
    111 => ['name' => '&Eacute;clat d\'améthyste vajrada', 'rank' => 2],
    112 => ['name' => '&Eacute;clat de turquoise', 'rank' => 2],
    113 => ['name' => '&Eacute;clat de jade shivada', 'rank' => 2],
    114 => ['name' => '&Eacute;clat de topaze prithiva', 'rank' => 2],
    115 => ['name' => 'Tuile cassée de Décabarian', 'rank' => 2],
    116 => ['name' => 'Dent de lait du Loup boréal', 'rank' => 2],
    117 => ['name' => 'Entraves du Chevalier du Croc de Lion', 'rank' => 2],
    118 => ['name' => 'Sable lumineux de Guyun', 'rank' => 2],
    119 => ['name' => 'Plomb karstique', 'rank' => 2],
    120 => ['name' => 'Grain d\'aérosidérite noire', 'rank' => 2],
    121 => ['name' => 'Branche marine de corail', 'rank' => 2],
    122 => ['name' => 'Sagesse de Narukami', 'rank' => 2],
    123 => ['name' => 'Masque du lieutenant pernicieux', 'rank' => 2],
    124 => ['name' => 'Masque sale', 'rank' => 2],
    125 => ['name' => 'Parchemin sigillé', 'rank' => 2],
    126 => ['name' => 'Pointe de flèche aiguisée', 'rank' => 2],
    127 => ['name' => 'Corne lourde', 'rank' => 2],
    128 => ['name' => 'Branche morte des lignes énergétiques', 'rank' => 2],
    129 => ['name' => 'Pollen d\'herbe brumeuse', 'rank' => 2],
    130 => ['name' => 'Dague de classe rituelle', 'rank' => 2],
    131 => ['name' => 'Insigne de sergent', 'rank' => 2],
    132 => ['name' => 'Mucus de Blob', 'rank' => 2],
    133 => ['name' => 'Nectar miroitant', 'rank' => 2],
    134 => ['name' => 'Fragment d\'os fragile', 'rank' => 2],
    135 => ['name' => 'Insigne de corbeau en argent', 'rank' => 2],
    136 => ['name' => 'Dispositif du chaos', 'rank' => 2],
    137 => ['name' => 'Garde-main kageuchi', 'rank' => 2],
    138 => ['name' => 'Engrenage du chaos', 'rank' => 2],
    139 => ['name' => 'Prisme sombre', 'rank' => 2],
    140 => ['name' => 'Coeur spectral', 'rank' => 2],
    141 => ['name' => 'Griffe dissimulée', 'rank' => 2],
    142 => ['name' => 'Enseignement de la Liberté', 'rank' => 2],
    143 => ['name' => 'Enseignement de la Résistance', 'rank' => 2],
    144 => ['name' => 'Enseignement de la Poésie', 'rank' => 2],
    145 => ['name' => 'Enseignement de la Prospérité', 'rank' => 2],
    146 => ['name' => 'Enseignement de la Diligence', 'rank' => 2],
    147 => ['name' => 'Enseignement de l\'Or', 'rank' => 2],
    148 => ['name' => 'Enseignement de l\'éphémère', 'rank' => 2],
    149 => ['name' => 'Enseignement de l\'élégance', 'rank' => 2],
    150 => ['name' => 'Enseignement de la lumière', 'rank' => 2],
    151 => ['name' => 'Masque endommagé', 'rank' => 1],
    152 => ['name' => 'Parchemin divinatoire', 'rank' => 1],
    153 => ['name' => 'Pointe de flèche robuste', 'rank' => 1],
    154 => ['name' => 'Insigne de nouvelle recrue', 'rank' => 1],
    155 => ['name' => 'Bave de Blob', 'rank' => 1],
    156 => ['name' => 'Nectar de Fleur mensongère', 'rank' => 1],
    157 => ['name' => 'Insigne du Pilleur', 'rank' => 1],
    158 => ['name' => 'Garde-main ancien', 'rank' => 1],
    159 => ['name' => 'Coquille spectrale', 'rank' => 1],
    160 => ['name' => 'Couronne de la sagesse', 'rank' => 5],
    161 => ['name' => 'Diamant scintillant', 'rank' => 5],
    162 => ['name' => 'Pierre d\'agate agnidus', 'rank' => 5],
    163 => ['name' => 'Pierre de lazurite narunada', 'rank' => 5],
    164 => ['name' => 'Pierre d\'améthyste vajrada', 'rank' => 5],
    165 => ['name' => 'Pierre de turquoise vayuda', 'rank' => 5],
    166 => ['name' => 'Pierre de jade shivada', 'rank' => 5],
    167 => ['name' => 'Pierre de topaze prithiva', 'rank' => 5],
    168 => ['name' => 'Rêve brisé de Décabarian', 'rank' => 5],
    169 => ['name' => 'Nostalgie du Loup boréal', 'rank' => 5],
    170 => ['name' => 'Idéaux du Chevalier du Croc de Lion', 'rank' => 5],
    171 => ['name' => 'Corps divin de Guyun', 'rank' => 5],
    172 => ['name' => 'Or karstique', 'rank' => 5],
    173 => ['name' => 'Morceau d\'aérosidérite noire', 'rank' => 5],
    174 => ['name' => 'Branche marine d\'or', 'rank' => 5],
    175 => ['name' => 'Vigillance de Narukami', 'rank' => 5],
    176 => ['name' => 'Masque du kijin', 'rank' => 5],
    177 => ['name' => 'Cécilia'],
    178 => ['name' => 'Ganoderma marin'],
    179 => ['name' => 'Moelle cristalline'],
    180 => ['name' => 'Herbe à lampe'],
    181 => ['name' => 'Scarabuto'],
    182 => ['name' => 'Fleur de cerisier'],
    183 => ['name' => 'Champignon anémophile'],
    184 => ['name' => 'Chrysanthème à aubes'],
    185 => ['name' => 'Jade noctiluque'],
    186 => ['name' => 'Coeur de lapis'],
    187 => ['name' => 'Fleur de Qingxin'],
    188 => ['name' => 'Lys calla'],
    189 => ['name' => 'Graines de pissenlit'],
    190 => ['name' => 'Perle de corail'],
    191 => ['name' => 'Fausse nageoire de l\'héritier du dragon', 'rank' => 4],
    192 => ['name' => 'Lys verni'],
    193 => ['name' => 'Conque d\'étoile'],
    194 => ['name' => 'Piment de Jueyun'],
    195 => ['name' => ''],
    196 => ['name' => ''],
    197 => ['name' => ''],
    198 => ['name' => ''],
    199 => ['name' => ''],
    200 => ['name' => '']
];
